CC="gcc"
CXX="g++"
CPP="cpp"
LD="ld.bfd"
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-Wl,-O2 -Wl,--as-needed"
RUSTFLAGS="-C debuginfo=0 -C codegen-units=1 -C target-cpu=native -C opt-level=3"

LC_MESSAGES=C.UTF-8

ACCEPT_KEYWORDS="~amd64"
RUBY_TARGETS="ruby40"
RUBY_SINGLE_TARGET="ruby40"
LUA_TARGETS="lua5-4"
LUA_SINGLE_TARGET="lua5-4"
PERL_FEATURES="ithreads"

ACCEPT_LICENSE="*"
VIDEO_CARDS="@VIDEO_CARDS@"
MAKEOPTS="-j@BUILD_JOBS@ -l@BUILD_LOAD@"
EMERGE_DEFAULT_OPTS="--jobs=@EMERGE_JOBS@ --load-average=@BUILD_LOAD@ --keep-going --verbose --with-bdeps=y --complete-graph=y --deep"
USE="-* minimal wayland pipewire clang native-symlinks lto pgo jit xs orc threads asm default-compiler-rt default-lld libcxx libcxxabi default-libcxx llvm-libunwind custom-cflags system-man system-libyaml system-lua system-bootstrap system-llvm system-lz4 system-sqlite system-ffmpeg system-icu system-av1 system-harfbuzz system-jpeg system-libevent system-librnp system-libvpx system-png system-python-libs system-webp system-ssl system-zlib system-boost system-zstd system-pipewire"
FEATURES="candy fixlafiles unmerge-orphans nodoc noman noinfo notitles parallel-install parallel-fetch clean-logs skiprocheck -ebuild-locks -merge-wait -keeptemp"
PORTAGE_COMPRESS_EXCLUDE_SUFFIXES="[1-9] n [013]p [1357]ssl"
PORTAGE_COMPRESS=gzip

CLEAN_DELAY="2"
