POLLY_FLAGS="-mllvm -polly \
-mllvm -polly-position=before-vectorizer \
-mllvm -polly-parallel \
-mllvm -polly-omp-backend=LLVM \
-mllvm -polly-vectorizer=stripmine \
-mllvm -polly-tiling \
-mllvm -polly-register-tiling \
-mllvm -polly-2nd-level-tiling \
-mllvm -polly-detect-keep-going \
-mllvm -polly-enable-delicm=true \
-mllvm -polly-dependences-computeout=2 \
-mllvm -polly-postopts=true \
-mllvm -polly-pragma-based-opts \
-mllvm -polly-pattern-matching-based-opts=true \
-mllvm -polly-reschedule=true \
-mllvm -enable-loop-distribute \
-mllvm -enable-unroll-and-jam \
-mllvm -polly-ast-use-context \
-mllvm -polly-invariant-load-hoisting \
-mllvm -polly-run-inliner \
-mllvm -polly-run-dce"

CC="clang"
CXX="clang++"
CPP="clang-cpp"
LD="ld.lld"
AR="llvm-ar"
NM="llvm-nm"
RANLIB="llvm-ranlib"
STRIP="llvm-strip"
OBJCOPY="llvm-objcopy"
OBJDUMP="llvm-objdump"

COMMON_FLAGS="-O3 -march=native -mtune=native -pipe -fno-math-errno \
        -flto=thin -fomit-frame-pointer -fno-semantic-interposition \
        -fno-stack-protector -fno-stack-clash-protection -fno-sanitize=all \
        -fno-dwarf2-cfi-asm -ffp-contract=fast ${POLLY_FLAGS}"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS} -stdlib=libc++"
LDFLAGS="-fuse-ld=lld -flto=thin -rtlib=compiler-rt -Wl,-O3 -Wl,--lto-O3 -Wl,--as-needed -Wl,--gc-sections -Wl,--icf=all -Wl,--strip-all -Wl,-z,norelro -Wl,--build-id=none -Wl,--relax -Wl,-z,noseparate-code -Wl,-znow"
RUSTFLAGS="-C debuginfo=0 -C target-cpu=native -C opt-level=3 -C codegen-units=1 -C strip=symbols"

LC_MESSAGES=C.UTF-8

ACCEPT_KEYWORDS="~amd64"
RUBY_TARGETS="ruby40"
RUBY_SINGLE_TARGET="ruby40"
LUA_TARGETS="lua5-4"
LUA_SINGLE_TARGET="lua5-4"
PERL_FEATURES="ithreads"

ACCEPT_LICENSE="*"
VIDEO_CARDS="@VIDEO_CARDS@"
MAKEOPTS="-j@BUILD_JOBS@ -l@BUILD_LOAD@"
EMERGE_DEFAULT_OPTS="--jobs=@EMERGE_JOBS@ --load-average=@BUILD_LOAD@ --keep-going --verbose --with-bdeps=y --complete-graph=y --deep"
USE="-* minimal wayland pipewire clang native-symlinks lto pgo jit xs orc threads asm default-compiler-rt default-lld libcxx libcxxabi default-libcxx llvm-libunwind custom-cflags system-man system-libyaml system-lua system-bootstrap system-llvm system-lz4 system-sqlite system-ffmpeg system-icu system-av1 system-harfbuzz system-jpeg system-libevent system-librnp system-libvpx system-png system-python-libs system-webp system-ssl system-zlib system-boost system-zstd system-pipewire"
FEATURES="candy fixlafiles unmerge-orphans nodoc noman noinfo notitles parallel-install parallel-fetch clean-logs skiprocheck -ebuild-locks -merge-wait -keeptemp"
PORTAGE_COMPRESS_EXCLUDE_SUFFIXES="[1-9] n [013]p [1357]ssl"
PORTAGE_COMPRESS=gzip

CLEAN_DELAY="2"
